Feature/task gui
it-top-shambala/pd011 pull request #1
Opened 2022-02-09 13:31 UTC by alcuritsin

Необходима проверка текущего состояния разработки UI.

2022-02-09 13:32 UTC, alcuritsin commented
![](https://github.trello.services/images/mini-trello-icon.png) [task_gui](https://trello.com/c/IvTQR1In/19-taskgui)

2022-02-09 13:36 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +    <Window.Resources>
Вынести в отдельный файл

2022-02-09 13:50 UTC, anst-foto requested changes
Исправить недочёты

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +        <ImageBrush x:Key="tb_selected"
Желательно использовать CamelCase (PascalCase) для именования или комбинацию CamelCase со snake_case
```suggestion
        <ImageBrush x:Key="ToggleButton_Selected"
```

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +        <Style TargetType="ToolTip" x:Key="tt_style">
Порядок следования аргументов лучше сделать единым
```suggestion
        <Style x:Key="ToolTip_Style" TargetType="ToolTip">
```

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +            BorderThickness="3">
Всё стилевое оформление выносится в отдельный файл

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +                                      Width="30"
Желательно от такого позиционирования элементов избавляться.

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +                                </EventTrigger>
Анимацию выносим в отдельный файл

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml
> +                        x:Name="LV"
Очень короткое имя

2022-02-09 13:50 UTC, anst-foto commented on PD011.App/MainWindow.xaml.cs
> +            // Set tooltip visibility
Комментирование кода для чего?

2022-02-09 14:20 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +    <Window.Resources>
Вынес стили в отдельный файл
https://github.com/itstep-shambala/pd011/commit/8471b48a83eff188b7b095ba912e236afad10735

2022-02-10 18:32 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +        <ImageBrush x:Key="tb_selected"
Выполнено

2022-02-10 18:32 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +        <Style TargetType="ToolTip" x:Key="tt_style">
Выполнено

2022-02-10 18:33 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +            BorderThickness="3">
Выполнено

2022-02-10 18:38 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +                                      Width="30"
От отрицательного значения избавился. На работу не повлияло.

2022-02-10 18:41 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +                                </EventTrigger>
Возникла проблема. Анимация запускается одним элементом, а изменяет свойства другого элемента обращаясь по имени. При вынесении в отдельный файл такая привязка становится не возможной. Найти решение этой проблемы мне не удалось.

2022-02-10 18:41 UTC, alcuritsin commented on PD011.App/MainWindow.xaml
> +                        x:Name="LV"
Имена все исправил.

2022-02-10 18:44 UTC, alcuritsin commented on PD011.App/MainWindow.xaml.cs
> +            // Set tooltip visibility
Это описание функции. Вынес его в summary...

2022-02-11 12:28 UTC, anst-foto commented on PD011.App/MainWindow.xaml.cs
> +    /// </summary>
В тегах автодокументирования можно писать и по русски )))

2022-02-11 12:42 UTC, anst-foto approved these changes
Отлично!

2022-02-11 12:57 UTC, merged