Feature/task db
it-top-shambala/pd011 pull request #2
Opened 2022-02-09 14:59 UTC by LeonenkoPavel1985

2022-02-09 15:04 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [task_db](https://trello.com/c/hyECEEmc/18-taskdb)

2022-02-09 15:09 UTC, alcuritsin commented on SQL/pd_011_libliry_SeregaSchugani.sql
> +CREATE TABLE table_user_role
Нет FOREIGN KEY. Так указывается связь таблиц.

2022-02-09 15:11 UTC, anst-foto requested changes
- Множество файлов. Нужно свести воедино.
- Расширение у файлов должно соответствовать типу содержимого.
- Диаграмма неполная.
- Разделить данные на два файла: **создание таблиц** и **наполнение таблиц**

2022-02-09 15:11 UTC, anst-foto commented on SQL/BookShop.sql
> +VALUE ('Фламинго');
Желательно на 2 разных файла разнести создание и наполнение таблиц

2022-02-09 15:11 UTC, anst-foto commented on SQL/BookShop.sql
> +VALUE ('Библиотекарь');
Посмотрите в сторону множественного добавления данных в таблицу
```sql
INSERT INTO tbl_name (a,b,c)
    VALUES (1,2,3), 
(4,5,6), 
(7,8,9);
```

2022-02-09 15:11 UTC, anst-foto commented on SQL/Part2.sql
> +
Для чего здесь столько комментариев?

2022-02-09 15:14 UTC, alcuritsin commented on SQL/BookShop.sql
> +    FOREIGN KEY (id_genre) REFERENCES table_genres (id),
К FOREIGN KEY можно добавить описание. Выглядит примерно вот так:
		CONSTRAINT FK_book_ganre
		FOREIGN KEY (id_genre) REFERENCES table_genres (id),
Это не обязательно 😄

2022-02-09 15:15 UTC, alcuritsin reviewed
В целом я ничего криминального не заметил.

2022-02-09 15:21 UTC, alcuritsin requested changes
- Добавить FOREGN KEY

2022-02-15 10:08 UTC, anst-foto requested changes
Смотрите замечения

2022-02-15 10:08 UTC, anst-foto commented on SQL/pd_011_create_table.sql
> +    FOREIGN KEY (id_genre) REFERENCES table_genres (id),
Не хватает правил `ON UPDATE` и `ON DELETE` для внешних ключей

2022-02-28 07:10 UTC, anst-foto approved these changes

2022-02-28 07:12 UTC, merged